# Generated by Django 5.0.7 on 2024-07-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_delete_clothes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
