# Generated by Django 5.0.7 on 2024-08-05 13:48

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '150x150', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
