# Generated by Django 5.0.7 on 2024-08-28 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproduct',
            name='favourite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_items', to='favourite.favourite'),
        ),
    ]
